1. Starting simplfied ver
```
 docker run -d --name elasticsearch -p 9200:9200 -e "discovery.type=single-node" -e "xpack.security.enabled=false" docker.elastic.co/elasticsearch/elasticsearch:8.12.0
```

2. Putting in document
```bash
curl -X PUT "localhost:9200/products"
```

3. Creating document with auto-id
```bash
curl -X POST "localhost:9200/products/_doc/" -H 'Content-Type: application/json' -d'
{"name": "Laptop", "price": 1000, "category": "electronics"} '
```

4. Add with assigned id
```bash
curl -X PUT "localhost:9200/products/_doc/100" -H 'Content-Type: application/json' -d'
{"name": "Smartphone", "price": 500, "category": "electronics"} '
```

5. Post update
```bash
curl -X POST "localhost:9200/products/_update/100" -H 'Content-Type: application/json' -d'
{"doc": {"price": 450}} '
```

6. Delete document
```bash
curl -X POST "localhost:9200/products/_update/100" -H 'Content-Type: application/json' -d'
{"doc": {"price": 450}} '
```

