version: '3.8'
services:
  db:
    image: postgres:15
    container_name: postgres_boss
    restart: always
    environment:
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_ui
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mail.com
      PGADMIN_DEFAULT_PASSWORD: admin_password
    ports:
      - "8080:80"
  flyway:
    image: flyway/flyway:9
    command: -url=jdbc:postgresql://db:5432/dbtest -user=postgres -password=1234 -connectRetries=60 migrate
    volumes:
      - ./Migrations:/flyway/sql 
    depends_on:
      - db
  postgres-exporter:
    image: prometheuscommunity/postgres-exporter
    container_name: postgres_exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://postgres:1234@db:5432/dbtest?sslmode=disable"
    ports:
      - "9187:9187"
    depends_on:
      - db

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
