version: '3.8'
services:
  db:
    image: postgres:15
    container_name: postgres_boss
    restart: always
    environment:
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_ui
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mail.com
      PGADMIN_DEFAULT_PASSWORD: admin_password
    ports:
      - "8080:80"